### ISSUE TITLE
Chunking data results in different hash to using the data non-chunked

### ISSUE THREAD

**Issue by mattmook** [catap/scala-blake3#1]
I have test data based on the official test vectors where I have a 64 byte array with each byte in the array having the value of its index. i.e. my input is an `Array[Byte]` with value `data = [0, 1, 2, …, 63]`

Running `Blake3.newHasher().update(data).doneHex(16)` results in `4eed7141ea4a5cd4` matching the expected result.

However, if instead I split the data into two 32-byte chunks, `data1 = [0, 1, …, 31]` and `data2 = [32, 32, …, 63]` and run `Blake3.newHasher().update(data1).update(data2).doneHex(16)` I should expect the same output but instead get `cdc46473e43a732a`.

Weirdly splitting a 63 byte array into 32 and 31 bytes and performing the same results in the correct data so I'm not sure if there's something funky going on that I'm missing.

The same can also be observed for other sized arrays of data, for example 128, 1024, 2048 when split in two.

I wrote the following test to show this in action, although I apologise for the code being in Kotlin, I'm not a Scala developer (yet)!

```
class Testing {
    @Test
    fun sixtyThree() {
        val hasher1 = Blake3.newHasher()
        hasher1.update(ByteArray(63) { it.toByte() })
        val expected = hasher1.doneHex(16)

        val hasher2 = Blake3.newHasher()
        hasher2.update(ByteArray(32) { it.toByte() })
        hasher2.update(ByteArray(31) { (it + 32).toByte() })
        val actual = hasher2.doneHex(16)

        // works as expected
        assertEquals(expected, actual)
    }

    @Test
    fun sixtyFour() {
        val hasher1 = Blake3.newHasher()
        hasher1.update(ByteArray(64) { it.toByte() })
        val expected = hasher1.doneHex(16)

        val hasher2 = Blake3.newHasher()
        hasher2.update(ByteArray(32) { it.toByte() })
        hasher2.update(ByteArray(32) { (it + 32).toByte() })
        val actual = hasher2.doneHex(16)

        // fails
        assertEquals(expected, actual)
    }
}
```

**Comment by mattmook** [comment]
I think updating ChunkState.update to the following fixes the problem although I've not tested this in Scala:

```scala
  def update(bytes: Array[Byte], from: Int, to: Int): Unit = {
    var i = from

    while (i < to) {
        compressIfRequired()

        val consume = Math.min(BLOCK_LEN - blockLen, to - i)

        System.arraycopy(bytes, i, block, blockLen, consume)
        blockLen += consume
        i += consume
    }
}
```

I also updated the update(byte) function to use the above so all code paths go through the same thing:

```
val oneByte: Array[Byte] = new Array[Byte](1)

def update(byte: Byte): Unit = {
    oneByte(0) = byte
    update(oneByte, 0, 1)
  }
```

**Comment by catap** [comment]
@mattmook thanks for report and sorry for very long reply. I haven't received any notification about it (!) and have discovered it right now.

**Comment by catap** [comment]
@mattmook about your code: `compressIfRequired()` walking over provided array, and `System.arraycopy` does the same way.

My implementation quite complicated but it allows to never copy a data on huge block that can be easy compressed.
